server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "resourceflow"
  sslmode: "disable"

ssh:
  user: "monitoring"
  password: "your-secure-password"
  timeout: 5

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0 