linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
  gofmt:
    simplify: true

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck 